version: '3.8'

services:
  server:
    build:
      context: ./server  # Path to your server Dockerfile
    ports:
      - "3000:3000"  # Adjust as needed
    depends_on:
      - redis
    env_file:
      - ./server/docker.env
    environment:
      - REDIS_PUBSUB_HOST=redis://redis:6379
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - NODE_ENV=docker  # Ensure the server uses the Redis service defined below

  client:
    build:
      context: ./client  # Path to your client Dockerfile
    ports:
      - "5173:5173"  # Port for the Vite React client
    depends_on:
      - server  # Optional: if client depends on server being up

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

# Optional networks section to isolate your containers
networks:
  default:
    driver: bridge