version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  server:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    environment:
      - REDIS_PUBSUB_HOST=redis://redis:6379
      - REDIS_PORT=6379
      - REDIS_HOST=redis
      - NODE_ENV=docker
    depends_on:
      - redis
