version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
  server:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - redis
